/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//RCC Register to enable Port C, Port D, PortG, andPort E
 #define rccAHB1Register *((volatile uint32_t*) 0x40023830)

// **** KEY PAD ***


// MODE register for Port C (Cols) and Port E (Rows)
#define modeRegPortC  *((volatile uint32_t*) 0x40020800)
#define modeRegPortE  *((volatile uint32_t*) 0x40021000)

// MODE register for Port C (Cols) and Port E (Rows)


// OUTPUT DATA register for Port E (Rows)
#define outputRegPortE *((volatile uint32_t*) 0x40021014)


// INPUT DATA register for Port C (Cols)
#define inputRegPortC *((volatile uint32_t* ) 0x40020810)



// PULlUP/PULLDOWN register for Port C (set to pull up)
#define pullRegPortC  *((volatile uint32_t*) 0x4002080C)




// *** LCD SCREEN ***

// MODE register for PORT G and PORT D

#define modeRegPortG  *((volatile uint32_t*) 0x40021800)
#define modeRegPortD  *((volatile uint32_t*) 0x40020C00)



// OUTPUT DATA register for Port G (PS and E Pins on LCD Display) and PORT D (Data pins)
#define outputRegPortG *((volatile uint32_t*) 0x40021814)
#define outputRegPortD  *((volatile uint32_t*) 0x40020C14) // This is used to send character data

#define PIN_D7 0x7
#define PIN_D6 0x5
#define PIN_D5 0x4
#define PIN_D4 0x2




void delay(uint32_t amount)
{
//	300,000 iterations ~= 150ms
	for(uint32_t i=0; i < amount; i++);
}

void enableEtoSend(){
	delay(100);
	outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command
	delay(50);
	outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command
	delay(50);

}

void clearDpins(){
	delay(50);
	outputRegPortD = outputRegPortD & ~(1 << PIN_D4);
	outputRegPortD = outputRegPortD & ~(1 << PIN_D5);
	outputRegPortD = outputRegPortD & ~(1 << PIN_D6);
	outputRegPortD = outputRegPortD & ~(1 << PIN_D7);
	delay(100);


}

void resetDisplay(){

		//	Sending 0000
		delay(150);
		outputRegPortD = outputRegPortD & ~(1 << 4); // clearing D5 (PD4)
		delay(100);

		outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command (0000)
		delay(50);
		outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command




		// Sending 0001
		delay(100);
		outputRegPortD = outputRegPortD | (1 << 2); // enabling D4(PD2)
		delay(50);
		outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command (0001)
		delay(50);
		outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command



	// Return Home

		//	Sending 0000
		delay(100);
		outputRegPortD = outputRegPortD & ~(1 << 2); // disabling D4(PD2)
		delay(50);

		outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command (0000)
		delay(50);
		outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command


		//	Sending 0010
		delay(100);
		outputRegPortD = outputRegPortD | (1 << 4); // enabling D5(PD4)

		delay(50);

		outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command (0001)
		delay(50);
		outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command
		outputRegPortD = outputRegPortD & ~(1 << 4); // disabling D4(PD2)



}


void sendLCDData(uint8_t data){

	uint8_t upperNibble = (data & 0xF0) >> 4;


	//	Enable RS
	outputRegPortG = outputRegPortG | (1 << 2); // enabling RS (PG2) to send data
	delay(100);



//	UPPER 4 bits
//	1st bit set
	if(upperNibble & 0x1 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D4);

	}
//	Second bit set

	if (upperNibble & 0x2 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D5);
	}

//	third bit set
	if (upperNibble & 0x4 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D6);
	}

//	fourth bit set
	if (upperNibble & 0x8 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D7);
	}

//	Send first 4 bits
	enableEtoSend();
	clearDpins();


//	LOWER 4 bits
//	1st bit set
	if(data & 0x1 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D4);

	}
//	Second bit set

	if (data & 0x2 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D5);
	}

//	third bit set
	if (data & 0x4 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D6);
	}

//	fourth bit set
	if (data & 0x8 ){
		outputRegPortD = outputRegPortD | (1 << PIN_D7);
	}

//	Send first 4 bits
	enableEtoSend();
	clearDpins();



	delay(100);
	outputRegPortG = outputRegPortG & ~(1 << 2); // disabling RS (PG2)

}




int main(void)
{

//	Enable RCC for AHB1 (PORT E,PORT C, PORT D, PORT G)
	rccAHB1Register = rccAHB1Register | 0x5C;

//	Set ROWS (Port E) to OUTPUT mode (PE2,PE3,PE4,PE5)
	modeRegPortE = modeRegPortE | (1 << 4); //PE2
	modeRegPortE = modeRegPortE | (1 << 6); //PE3
	modeRegPortE = modeRegPortE | (1 << 8); //PE4
	modeRegPortE = modeRegPortE | (1 << 10); //PE5

// Set COLS to INPUT mode
	modeRegPortC = modeRegPortC | 0x00000000;

//	Set COLS (Port C) to PULL UP (PC8, PC11, PC12, PC13)
	pullRegPortC = pullRegPortC | (1 << 16); //PC8
	pullRegPortC = pullRegPortC | (1 << 22); //PC11
	pullRegPortC = pullRegPortC | (1 << 24); //PC12
	pullRegPortC = pullRegPortC | (1 << 26); //PC13

//	*** Setting up LCD Screen ***

// Set PG2, PG3 to Output Mode
	modeRegPortG = modeRegPortG | (1<<4); // PG2
	modeRegPortG = modeRegPortG | (1 << 6); // PG3

// Set PD2, PD4, PD5, and PD7 to output mode

	modeRegPortD = modeRegPortD | (1 << 4); // PD2
	modeRegPortD = modeRegPortD | (1 << 8); // PD4
	modeRegPortD = modeRegPortD | (1 << 10); // PD5
	modeRegPortD = modeRegPortD | (1 << 14); // PD7


// Change LCD Display into 4-bit mode

	delay(100);
	outputRegPortD = outputRegPortD | (1 << 4); // enabling D5 (PD4) to send 0100
	delay(50);


	outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command
	delay(50);
	outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command

//	//	Sending 0000
//	delay(100);
//	outputRegPortD = outputRegPortD & ~(1 << 4); // clearing D5 (PD4)
//	delay(50);
//
//	outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command (0000)
//	delay(50);
//	outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command


//	Clear display
	resetDisplay();


// Display On cursor, Blinking
	//	Sending 0000
	delay(100);

	outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command (0000)
	delay(50);
	outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command
	delay(100);

//			Sending 1111
	outputRegPortD = outputRegPortD | (1 << 7); // enabling D7 (PD7) to send 1111
	outputRegPortD = outputRegPortD | (1 << 5); // enabling D6 (PD5) to send 1111
	outputRegPortD = outputRegPortD | (1 << 4); // enabling D5 (PD4) to send 1111
//	outputRegPortD = outputRegPortD | (1 << 2); // enabling D4 (PD2) to send 1111


	delay(100);
	outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command
	delay(50);
	outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command

//	Clearing D pins
	outputRegPortD = outputRegPortD & ~(1 << 7); // disabling D7 (PD7)
	outputRegPortD = outputRegPortD & ~(1 << 5); // disabling D6 (PD5)
	outputRegPortD = outputRegPortD & ~(1 << 4); // disabling D5 (PD4)
//	outputRegPortD = outputRegPortD & ~(1 << 2); // disabling D4 (PD2)





	while(1){
//		Keep ROWS (PORT E) in HIGH mode (PE2,PE3,PE4,PE5)
		outputRegPortE = outputRegPortE | 0x3C;

//		Make R1 (PE2) LOW STATE
		outputRegPortE = outputRegPortE & ~(1 << 2);

//
		if((inputRegPortC & (1 << 13)) == 0){
			delay(300000);
			sendLCDData(0x31);

//
////			Enable RS
//			outputRegPortG = outputRegPortG | (1 << 2); // enabling RS (PG2) to send data
//			delay(100);
//
////			Send 0011
//
//			outputRegPortD = outputRegPortD | (1 << 4); // enabling D5 (PD4) to send 0011
//			outputRegPortD = outputRegPortD | (1 << 2); // enabling D4 (PD2) to send 0011
//
//
//			delay(100);
//			outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command
//			delay(50);
//			outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command
//
//			outputRegPortD = outputRegPortD & ~(1 << 4); // disabling D5 (PD4)
//			outputRegPortD = outputRegPortD & ~(1 << 2); // disabling D4 (PD2)
//
////			Send 0001
//			delay(100);
//
//			outputRegPortD = outputRegPortD | (1 << 2); // enabling D4 (PD2) to send 0001
//			delay(100);
//			outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command
//			delay(50);
//			outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command
//
//			outputRegPortD = outputRegPortD & ~(1 << 2); // disabling D4 (PD2)
//
//
//			delay(100);
//			outputRegPortG = outputRegPortG & ~(1 << 2); // disabling RS (PG2)



			printf("1\n");

		} else if((inputRegPortC & (1 << 12)) == 0)
		{
			delay(300000);
			sendLCDData(0x32);

			printf("2\n");

		} else if((inputRegPortC & (1 << 11)) == 0)
		{
			delay(300000);
			sendLCDData(0x33);


			printf("3\n");

		}else if((inputRegPortC & (1 << 8)) == 0)
		{
			delay(300000);
			sendLCDData(0x41);



////			Enable RS
//			outputRegPortG = outputRegPortG | (1 << 2); // enabling RS (PG2) to send data
//			delay(100);
//
////			Send 0100
//
//			outputRegPortD = outputRegPortD | (1 << 5); // enabling D6 (PD5) to send 0011
//
//
//			delay(100);
//			outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command
//			delay(50);
//			outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command
//
//
//			outputRegPortD = outputRegPortD & ~(1 << 5); // disabling D6 (PD5)
//
////			Send 0001
//			delay(100);
//
//			outputRegPortD = outputRegPortD | (1 << 2); // enabling D4 (PD2) to send 0001
//			delay(100);
//			outputRegPortG = outputRegPortG | (1 << 3); // enabling E (PG3) to send command
//			delay(50);
//			outputRegPortG = outputRegPortG & ~(1 << 3); // disabling E (PG3) to send command
//
//			outputRegPortD = outputRegPortD & ~(1 << 2); // disabling D4 (PD2)
//
//
//			delay(100);
//			outputRegPortG = outputRegPortG & ~(1 << 2); // disabling RS (PG2)

			printf("A\n");
		}



//		Keep ROWS (PORT E) in HIGH mode (PE2,PE3,PE4,PE5)
		outputRegPortE = outputRegPortE | 0x3C;

//		Make R2 (PE3) LOW STATE
		outputRegPortE = outputRegPortE & ~(1 << 3);

//
		if((inputRegPortC & (1 << 13)) == 0){
			delay(300000);
			sendLCDData(0x34);

			printf("4\n");

		} else if((inputRegPortC & (1 << 12)) == 0)
		{
			delay(300000);
			sendLCDData(0x35);

			printf("5\n");

		} else if((inputRegPortC & (1 << 11)) == 0)
		{
			delay(300000);
			sendLCDData(0x36);

			printf("6\n");

		}else if((inputRegPortC & (1 << 8)) == 0)
		{
			delay(300000);
			sendLCDData(0x42);

			printf("B\n");
		}



//		Keep ROWS (PORT E) in HIGH mode (PE2,PE3,PE4,PE5)
		outputRegPortE = outputRegPortE | 0x3C;

//		Make R3 (PE4) LOW STATE
		outputRegPortE = outputRegPortE & ~(1 << 4);

//
		if((inputRegPortC & (1 << 13)) == 0){
			delay(300000);
			sendLCDData(0x37);

			printf("7\n");

		} else if((inputRegPortC & (1 << 12)) == 0)
		{
			delay(300000);
			sendLCDData(0x38);

			printf("8\n");

		} else if((inputRegPortC & (1 << 11)) == 0)
		{
			delay(300000);
			sendLCDData(0x39);

			printf("9\n");

		}else if((inputRegPortC & (1 << 8)) == 0)
		{
			delay(300000);
			sendLCDData(0x43);

			printf("C\n");
		}


//		Keep ROWS (PORT E) in HIGH mode (PE2,PE3,PE4,PE5)
		outputRegPortE = outputRegPortE | 0x3C;

//		Make R4 (PE5) LOW STATE
		outputRegPortE = outputRegPortE & ~(1 << 5);

//
		if((inputRegPortC & (1 << 13)) == 0){
			delay(300000);
			resetDisplay();

			printf("*\n");

		} else if((inputRegPortC & (1 << 12)) == 0)
		{
			delay(300000);
			sendLCDData(0x30);

			printf("0\n");

		} else if((inputRegPortC & (1 << 11)) == 0)
		{
			delay(300000);
			sendLCDData(0x23);

			printf("#\n");

		}else if((inputRegPortC & (1 << 8)) == 0)
		{
			delay(300000);
			sendLCDData(0x44);

			printf("D\n");
		}



	};

}
